# Generated by Django 4.2.30 on 2026-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_payment_id_book_payment_status_book_total_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='book',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AddField(
            model_name='book',
            name='upi_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
