# Generated by Django 4.2.30 on 2026-06-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_user_book_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=30),
        ),
    ]
